version: "3.11"

services:
  app: # Django 파트
    build:
      context: .
    restart: always
    volumes:
      - static-data:/vol/web
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
    depends_on:
      - db

  db: # PostgreSQL 파트 -> AWS RDS 파트
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  proxy: # nginx 파트
    build:
      context: ./proxy # 실행하는 폴더
    restart: always
    depends_on:
      - app
    ports:
      - 80:8000 # ec2-123-123-123.com/api/v1 (from:to)
      # - 8000:8000 #로컬에서 테스트시
    volumes:
      - static-data:/vol/static

	# redis 추가시
  # redis:
  #   build:
  #     context: ./proxy
  #   restart: always
  #   depends_on:
  #     - app
  #   ports:
  #     - 80:8000
  #   volumes:
  #     - static-data:/vol/static

volumes:
  postgres-data:
  static-data: